SHOW VARIABLES LIKE 'secure_file_priv';
USE universite;
SHOW TABLES;
SELECT COUNT(*) FROM ETUDIANT;
SELECT * 
INTO OUTFILE 'C:/temp/etudiants.csv'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
FROM ETUDIANT;
SHOW INDEX FROM INSCRIPTION;

ALTER TABLE INSCRIPTION 
ADD INDEX idx_date_inscription(date_inscription);

ALTER TABLE ETUDIANT 
ADD INDEX idx_nom(nom);

ALTER TABLE INSCRIPTION 
ADD INDEX idx_etudiant_date(etudiant_id, date_inscription);

SHOW INDEX FROM INSCRIPTION;
SHOW INDEX FROM ETUDIANT;
ALTER TABLE INSCRIPTION 
DROP INDEX idx_date_inscription;
EXPLAIN
SELECT e.nom, e.prenom, COUNT(i.id) as nb_inscriptions
FROM ETUDIANT e
JOIN INSCRIPTION i ON i.etudiant_id = e.id
GROUP BY e.id
ORDER BY nb_inscriptions DESC;

EXPLAIN FORMAT=JSON
SELECT e.nom, e.prenom, COUNT(i.id) as nb_inscriptions
FROM ETUDIANT e
JOIN INSCRIPTION i ON i.etudiant_id = e.id
GROUP BY e.id
ORDER BY nb_inscriptions DESC;
ANALYZE TABLE INSCRIPTION;
ANALYZE TABLE ETUDIANT;
ANALYZE TABLE COURS;
OPTIMIZE TABLE INSCRIPTION;
OPTIMIZE TABLE ETUDIANT;
SELECT 
    TABLE_NAME,
    TABLE_ROWS,
    DATA_LENGTH,
    INDEX_LENGTH,
    ROUND(INDEX_LENGTH/DATA_LENGTH*100, 2) as index_ratio_percent
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'universite'
ORDER BY TABLE_NAME;
USE universite;

SHOW TABLES;

ALTER TABLE INSCRIPTION ADD INDEX idx_test(date_inscription);

EXPLAIN SELECT * FROM INSCRIPTION WHERE date_inscription > '2024-01-01';

ANALYZE TABLE INSCRIPTION;

SHOW INDEX FROM INSCRIPTION;

ALTER TABLE INSCRIPTION DROP INDEX idx_test;

SELECT * FROM ETUDIANT;

SELECT * INTO OUTFILE 'C:/temp/export_final.csv'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
FROM ETUDIANT;
CREATE TABLE INSCRIPTION (
    id INT PRIMARY KEY AUTO_INCREMENT,
    etudiant_id INT,
    cours_id INT,
    date_inscription DATE
);
